gtk3_deps:
  build: .
  environment:
    SERVER_LOG_MINIMAL: 1
    SERVER_APP_NAME: gtk3-deps
    S6_KILL_FINISH_MAXTIME: 1
    S6_KILL_GRACETIME: 1
    SERVER_WORKER_PROCESSES: 1
  volumes:
   - ./container/root/tests/goss.gtk3_deps.yaml:/goss.gtk3_deps.yaml

