version: "2"

services:
  base_gtk3_deps:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SCARLETT_ENABLE_SSHD: 0
        SCARLETT_ENABLE_DBUS: 'true'
        SCARLETT_BUILD_GNOME: 'true'
        TRAVIS_CI: 'true'
        STOP_AFTER_GOSS_GTK_DEPS: 'true'
        SKIP_GOSS_TESTS_GTK_DEPS: 'true'
    environment:
      SERVER_LOG_MINIMAL: 1
      SERVER_APP_NAME: base-gtk3-deps
      COMPOSE_PROJECT_NAME: base-gtk3-deps
      S6_KILL_FINISH_MAXTIME: 1
      S6_KILL_GRACETIME: 1
      SERVER_WORKER_PROCESSES: 1
      # NOTE: This enables SSHD access inside of the container for dev purposes
      # 1 = false
      # 0 = true
      SCARLETT_ENABLE_SSHD: 0
      SCARLETT_ENABLE_DBUS: 'true'
      SCARLETT_BUILD_GNOME: 'true'
      TRAVIS_CI: 'true'
      STOP_AFTER_GOSS_GTK_DEPS: 'true'
      SKIP_GOSS_TESTS_GTK_DEPS: 'true'
    volumes:
    - ./container/root/tests/gtk3_deps.yaml:/gtk3_deps.yaml
    ports:
    - "2222:22"
